# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.C = QtWidgets.QPushButton(self.centralwidget)
        self.C.setGeometry(QtCore.QRect(50, 190, 100, 200))
        self.C.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.C.setText("")
        self.C.setObjectName("C")
        self.D = QtWidgets.QPushButton(self.centralwidget)
        self.D.setGeometry(QtCore.QRect(150, 190, 100, 200))
        self.D.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.D.setText("")
        self.D.setObjectName("D")
        self.E = QtWidgets.QPushButton(self.centralwidget)
        self.E.setGeometry(QtCore.QRect(250, 190, 100, 200))
        self.E.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.E.setText("")
        self.E.setObjectName("E")
        self.F = QtWidgets.QPushButton(self.centralwidget)
        self.F.setGeometry(QtCore.QRect(350, 190, 100, 200))
        self.F.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.F.setText("")
        self.F.setObjectName("F")
        self.G = QtWidgets.QPushButton(self.centralwidget)
        self.G.setGeometry(QtCore.QRect(450, 190, 100, 200))
        self.G.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.G.setText("")
        self.G.setObjectName("G")
        self.B = QtWidgets.QPushButton(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(650, 190, 100, 200))
        self.B.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.B.setText("")
        self.B.setObjectName("B")
        self.A = QtWidgets.QPushButton(self.centralwidget)
        self.A.setGeometry(QtCore.QRect(550, 190, 100, 200))
        self.A.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.A.setText("")
        self.A.setObjectName("A")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(120, 190, 61, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(37, 37, 37);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(219, 190, 61, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(37, 37, 37);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(419, 190, 61, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(37, 37, 37);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(520, 190, 61, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(37, 37, 37);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(620, 190, 61, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(37, 37, 37);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.D.raise_()
        self.C.raise_()
        self.E.raise_()
        self.F.raise_()
        self.G.raise_()
        self.B.raise_()
        self.A.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
